const data = {
    products: [
        {
            _id: '1',
            name: 'Baby Girls Casual',
            category: 'skirt and top',
            image: '/images/p1.jpg',
            price: 920,
            countInStock: 10,
            brand: 'wikky',
            rating: 4.0,
            numReviews: 10,
            description: 'great product with super quality',
          },
          {
            _id: '2',
            name: 'Baby girl Wear',
            category: 'skirt and tops',
            image: '/images/p2.jpg',
            price: 1200,
            countInStock: 20,
            brand: 'poppy',
            rating: 4.0,
            numReviews: 10,
            description: 'mild and comfort product',
          },
          {
            _id: '3',
            name: 'Cutie skirt and top',
            category: 'skirt and tops',
            image: '/images/p3.jpg',
            price: 900,
            countInStock: 10,
            brand: 'Luxury',
            rating: 3.0,
            numReviews: 17,
            description: 'high quality product',
          },
          {
            _id: '4',
            name: 'soft skirts',
            category: 'skirt and tops',
            image: '/images/p4.jpg',
            price: 780,
            countInStock: 10,
            brand: 'pooma',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
          },
          {
            _id: '5',
            name: 'Dark Chocolate',
            category: 'chocolate',
            image: '/images/p5.jpg',
            price: 700,
            countInStock: 10,
            brand: 'merrywell',
            rating: 4.5,
            numReviews: 10,
            description: 'supreme quality chocolates',
          },
          {
            _id: '6',
            name: 'nuts filled chocolate',
            category: 'chocolate',
            image: '/images/p6.jpg',
            price: 930,
            countInStock: 10,
            brand: 'alaha',
            rating: 4.9,
            numReviews: 15,
            description: 'supreme quality chocolates',
          },
          {
            _id: '7',
            name: 'Nuts Chocolate',
            category: 'chocolate',
            image: '/images/p7.jpeg',
            price: 930,
            countInStock: 10,
            brand: 'alaha',
            rating: 4.9,
            numReviews: 15,
            description: 'supreme quality chocolates',
          },
          {
            _id: '8',
            name: 'Ferrero Rocher',
            category: 'chocolate',
            image: '/images/p8.jpg',
            price: 990,
            countInStock: 10,
            brand: 'ferrero rocher',
            rating: 4.5,
            numReviews: 15,
            description: 'supreme quality chocolates',
          },
    ],
  };
  export default data;